#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=segformer
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=5:58:59
#SBATCH --output=outputs/hyperbolic_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source activate hypseg

cd /home/mvlasenko/hyperbolic/hyp-segmentation || exit

cp -r /home/mvlasenko/hyperbolic/PartImageNet $TMPDIR/
echo "Files copied to $TMPDIR"

python3 lightning_segformer.py \
  --dataset_dir $TMPDIR/PartImageNet/ \
  --granularity subpart \
  --learning_rate 0.0001 \
  --num_epochs 50 \
  --batch_size 8 \
  --num_workers 8 \
  --accumulate_grad_batches 2 \
  --model_name "nvidia/segformer-b4-finetuned-ade-512-512"
